---
apiVersion: v1
kind: Namespace
metadata:
  name: collector-two
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: collector-two
data:
  server8888.conf: |
    server {
       listen 8888;

       location / {
          default_type text/plain;
          expires -1;
          return 200 'Server address: $server_addr:$server_port\nServer name: $hostname\nDate: $time_local\nURI: $request_uri\nRequest ID: $request_id\n';
       }
    }
  server9999.conf: |
    server {
       listen 9999;

       location / {
          default_type text/plain;
          expires -1;
          return 200 'Server address: $server_addr:$server_port\nServer name: $hostname\nDate: $time_local\nURI: $request_uri\nRequest ID: $request_id\n';
       }
    }
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  namespace: collector-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
       - name: nginx
         image: nginx
         volumeMounts:
          - name: mynginx-config
            mountPath: "/etc/nginx/conf.d"
            readOnly: true
      volumes:
         - name: mynginx-config
           configMap:
             name: nginx-conf
...
---
apiVersion: v1
kind: Service
metadata:
  name: collector 
  namespace: collector-two
spec:
  ports:
  - name: port8888
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: port9999
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: prod-app
  type: ClusterIP
...
